export const ROUTES = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/profile/change-password",
  MFA_SETUP: "/mfa/setup",
  MFA_DISABLE: "/mfa/disable",
  USERS: "/users",
  USER_NEW: "/users/new",
  USER_EDIT: (id: string) => `/users/${id}/edit`,
  USER_DETAIL: (id: string) => `/users/${id}`,
  ROLES: "/roles",
  ROLE_NEW: "/roles/new",
  ROLE_EDIT: (id: string) => `/roles/${id}/edit`,
  ROLE_DETAIL: (id: string) => `/roles/${id}`,
  INVENTORY: "/inventory",
  INVENTORY_CATEGORIES: "/inventory/categories",
  INVENTORY_WAREHOUSES: "/inventory/warehouses",
  INVENTORY_STOCK: "/inventory/stock",
  INVENTORY_MOVEMENTS: "/inventory/movements",
  ORDERS: "/orders",
  PROCUREMENT: "/procurement",
  CUSTOMERS: "/customers",
  CUSTOMER_DETAIL: (id: string) => `/customers/${id}`,
  CUSTOMER_EDIT: (id: string) => `/customers/${id}/edit`,
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  ORDER_NEW: "/orders/new",
  VENDORS: "/vendors",
  VENDOR_DETAIL: (id: string) => `/vendors/${id}`,
  PROCUREMENT_DETAIL: (id: string) => `/procurement/${id}`,
  PROCUREMENT_NEW: "/procurement/new",
  FINANCE: "/finance",
  MANUFACTURING: "/manufacturing",
  CRM: "/crm",
  HR: "/hr",
  REPORTS: "/reports",
  SETTINGS: "/settings",
  AUDIT: "/audit",
  FORBIDDEN: "/403",
} as const;

export const PERMISSIONS = {
  USER_CREATE: "user:create",
  USER_READ: "user:read",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_MANAGE_ROLES: "user:manage_roles",
  ROLE_CREATE: "role:create",
  ROLE_READ: "role:read",
  ROLE_UPDATE: "role:update",
  ROLE_DELETE: "role:delete",
  ORG_READ: "organization:read",
  ORG_UPDATE: "organization:update",
  ORG_DELETE: "organization:delete",
  INVENTORY_READ: "inventory:read",
  INVENTORY_CREATE: "inventory:create",
  INVENTORY_UPDATE: "inventory:update",
  INVENTORY_DELETE: "inventory:delete",
  CUSTOMER_READ: "customer:read",
  CUSTOMER_CREATE: "customer:create",
  CUSTOMER_UPDATE: "customer:update",
  CUSTOMER_DELETE: "customer:delete",
  ORDER_READ: "order:read",
  ORDER_CREATE: "order:create",
  ORDER_UPDATE: "order:update",
  ORDER_DELETE: "order:delete",
  ORDER_APPROVE: "order:approve",
  FINANCE_READ: "finance:read",
  FINANCE_CREATE: "finance:create",
  FINANCE_UPDATE: "finance:update",
  FINANCE_DELETE: "finance:delete",
  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export",
  INVENTORY_TRANSFER: "inventory:transfer",
  INVENTORY_ADJUST: "inventory:adjust",
  WAREHOUSE_READ: "warehouse:read",
  WAREHOUSE_CREATE: "warehouse:create",
  WAREHOUSE_UPDATE: "warehouse:update",
  WAREHOUSE_DELETE: "warehouse:delete",
  VENDOR_READ: "vendor:read",
  VENDOR_CREATE: "vendor:create",
  VENDOR_UPDATE: "vendor:update",
  VENDOR_DELETE: "vendor:delete",
  PROCUREMENT_READ: "procurement:read",
  PROCUREMENT_CREATE: "procurement:create",
  PROCUREMENT_UPDATE: "procurement:update",
  PROCUREMENT_DELETE: "procurement:delete",
  PROCUREMENT_APPROVE: "procurement:approve",
  PROCUREMENT_RECEIVE: "procurement:receive",
  SETTINGS_READ: "settings:read",
  SETTINGS_UPDATE: "settings:update",
  ADMIN_READ: "admin:read",
} as const;

export const USER_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  PENDING: "pending",
  SUSPENDED: "suspended",
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export const CACHE_KEYS = {
  USERS: ["users"],
  USER: (id: string) => ["users", id],
  CURRENT_USER: ["auth", "me"],
  ROLES: ["roles"],
  ROLE: (id: string) => ["roles", id],
  PERMISSIONS: ["permissions"],
  DASHBOARD_STATS: ["dashboard", "stats"],
  AUDIT_LOGS: ["audit-logs"],
  AUDIT_LOGS_ENTITY: (type: string, id: string) => ["audit-logs", type, id],
  AUDIT_LOGS_USER: (userId: string) => ["audit-logs", "user", userId],
  ORGANIZATION: ["organizations", "current"],
  ORG_SETTINGS: ["organizations", "settings"],
  ORG_STATS: ["organizations", "stats"],
  INVENTORY_ITEMS: ["inventory", "products"],
  INVENTORY_ITEM: (id: string) => ["inventory", "products", id],
  CATEGORIES: ["inventory", "categories"],
  CATEGORY: (id: string) => ["inventory", "categories", id],
  WAREHOUSES: ["warehouses"],
  WAREHOUSE: (id: string) => ["warehouses", id],
  STOCK: ["inventory", "stock"],
  MOVEMENTS: ["inventory", "movements"],
  CUSTOMERS: ["customers"],
  CUSTOMER: (id: string) => ["customers", id],
  CUSTOMER_ADDRESSES: (id: string) => ["customers", id, "addresses"],
  CUSTOMER_CONTACTS: (id: string) => ["customers", id, "contacts"],
  CUSTOMER_NOTES: (id: string) => ["customers", id, "notes"],
  ORDERS: ["orders"],
  ORDER: (id: string) => ["orders", id],
  ORDER_TIMELINE: (id: string) => ["orders", id, "timeline"],
  ORDER_DELIVERIES: (id: string) => ["orders", id, "deliveries"],
  VENDORS: ["vendors"],
  VENDOR: (id: string) => ["vendors", id],
  VENDOR_CONTACTS: (id: string) => ["vendors", id, "contacts"],
  VENDOR_CONTRACTS: (id: string) => ["vendors", id, "contracts"],
  VENDOR_PURCHASE_ORDERS: (id: string) => ["vendors", id, "purchase-orders"],
  PURCHASE_ORDERS: ["purchase-orders"],
  PURCHASE_ORDER: (id: string) => ["purchase-orders", id],
  PURCHASE_ORDER_TIMELINE: (id: string) => ["purchase-orders", id, "timeline"],
} as const;
